### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by ClearSeve** [miao1007/mieru#1]
```
E:\Data\Desktop\mieru>python3 calc.py book.txt
Traceback (most recent call last):
  File "E:\Data\Desktop\mieru\calc.py", line 6, in <module>
    from curses.ascii import NUL
  File "C:\Users\ClearSeve\AppData\Local\Programs\Python\Python311-32\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by ClearSeve** [comment]
run
```
pip install windows-curses
```
